name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout o código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Instala dependências
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Executa os testes
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      # Executa a aplicação
      - name: Run application
        run: |
          source venv/bin/activate
          python app.py
